[package]
name = "simple-sds"
version = "0.1.0"
authors = ["Jouni Siren <jouni.siren@iki.fi>"]
edition = "2018"
description = "Basic succinct data structures."
license = "MIT"
readme = "README.md"
repository = "https://github.com/jltsiren/simple-sds"

[features]
bench = ["getopts", "libc", "rand"]

[dependencies]
getopts = { version = "0.2", optional = true }
libc = { version = "0.2", optional = true }
rand = { version = "0.7", optional = true }

[dev-dependencies]
rand = "0.7"

[[bin]]
name = "benchmark"
required-features = ["bench"]
test = false
bench = false
doc = false